name: Bug Report
description: Recommended template for a detailed bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: Description, steps to reproduce, expected behavior, etc.

  - type: input
    id: repo_link
    attributes:
      label: Link to the source code using the tool
      description: Attach a link to your esbuild setup for context
      placeholder: https://github.com/<user>/<repo>

  - type: textarea
    id: json_file
    attributes:
      label: JSON esbuild metafile upload
      description: Drag your .json file here and GitHub will attach it.
      render: markdown
